FROM golang:alpine

# App Args
ARG APP_ENV
ARG APP_PORT

# DB Args
ARG DB_HOST
ARG DB_PORT
ARG DB_USER
ARG DB_PASSWORD
ARG DB_NAME

# Redis Args
ARG REDIS_HOST
ARG REDIS_PORT
ARG REDIS_PASSWORD

# JWT Args
ARG JWT_SECRET
ARG JWT_ISSUER
ARG JWT_CLAIMS_KEY

# App Envs
ENV APP_ENV=${APP_ENV}
ENV APP_PORT=${APP_PORT}

# DB Envs
ENV DB_HOST=${DB_HOST}
ENV DB_PORT=${DB_PORT}
ENV DB_USER=${DB_USER}
ENV DB_PASSWORD=${DB_PASSWORD}
ENV DB_NAME=${DB_NAME}

# Redis Envs
ENV REDIS_HOST=${REDIS_HOST}
ENV REDIS_PORT=${REDIS_PORT}
ENV REDIS_PASSWORD=${REDIS_PASSWORD}

# JWT Envs
ENV JWT_SECRET=${JWT_SECRET}
ENV JWT_ISSUER=${JWT_ISSUER}
ENV JWT_CLAIMS_KEY=${JWT_CLAIMS_KEY}

RUN apk update && apk add alpine-sdk git && rm -rf /var/cache/apk/*

WORKDIR /app

COPY go.mod .
COPY go.sum .

RUN go mod download

COPY . .

RUN go build -o ./server

EXPOSE 80

ENTRYPOINT ["./server"]
